{
  // Name and the location of the parser which will be generated.
  parserClass="tech.vhrd.vhl.VhlParser"
  // All nodes will extend this class. This wraps AST node to a PSI node.
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  // Prefix for all generated classes.
  psiClassPrefix="Vhl"
  // Suffix for implementation classes.
  psiImplClassSuffix="Impl"

  // Location to be used when generating PSI classes.
  psiPackage="tech.vhrd.vhl.psi"
  // Location to be used when generating PSI implementation classes.
  psiImplPackage="tech.vhrd.vhl.psi.impl"

  // Element type holder class name. This class will be used extensively throughout the tutorial.
  elementTypeHolderClass="tech.vhrd.vhl.psi.VhlTypes"

  // Class which will be used to create internal nodes.
  elementTypeClass="tech.vhrd.vhl.psi.VhlElementType"
  // Class which will be used to create leaf nodes.
  tokenTypeClass="tech.vhrd.vhl.psi.VhlTokenType"
}

vhlFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY